exp_name: CircleRegressorExperiment
run_name: circle_exp_1
random_state: 100
model_params:
  N_epoch: 20
  n_layers: 3
  dropout_rate: 0.2
  hidden_size: 16
  lr: 0.001
  input_size: 2
  output_size: 1
loader_name: CircleData
loader_params:
  batch_size: 16
  N_data: 1000
  test_split: 0.1
  circle_noise: 0.05
  circle_factor: 0.5
