exp_name: CircleLogisticRegressionExperiment
run_name: circle_exp_visualization_5
random_state: 100
use_wandb: True
log_progress: True
model_params:
  N_epoch: 100
  n_layers: 3
  dropout_rate: 0.0
  hidden_size: 8
  lr: 0.001
  input_size: 2
  output_size: 2
loader_name: CircleData
loader_params:
  batch_size: 128
  N_data: 3000
  test_split: 0.1
  circle_noise: 0.05
  circle_factor: 0.5
