exp_name: MNIST_MLP_Experiment
run_name: mnist_mlp_exp_1
random_state: 100
use_wandb: True
model_params:
  N_epoch: 10
  n_layers: 3
  dropout_rate: 0.2
  hidden_size: 64
  lr: 0.001
  input_size: 784
  output_size: 10
loader_params:
  batch_size: 128
